# Copyright 2015 The Kubernetes Authors. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
FROM {{ image_spec("base-tools") }}

# so apt-get doesn't complain
ENV DEBIAN_FRONTEND=noninteractive

#Go specific
ENV GOPATH=/golang
ENV CGO_ENABLED=0
ENV GOOS=linux
ADD server /golang/src/k8s.io/contrib/election/
ADD run.sh /run.sh

RUN \
  apt-get update && \
  apt-get install -t jessie-backports -y ca-certificates golang-go git && \
  go build -a -installsuffix cgo -ldflags '-w' -o /server /golang/src/k8s.io/contrib/election/main.go  && \
  chmod 755 /run.sh

#cleanup
RUN apt-get autoremove -y golang-go git && \
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /golang
